export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children, users, revenue, notifications, login}: {
    children: React.ReactNode;
    users: React.ReactNode;
    revenue: React.ReactNode;
    notifications: React.ReactNode;
    login: React.ReactNode;
}) {
    const isLoggedIn = true;
    return isLoggedIn?(
        <html lang="en">
        <body>
            <div>
                <div>{children}</div>
                <div style={{display: "flex"}}>
                    <div style={{display: "flex", flexDirection: "column"}}>
                        <div>{users}</div>
                        <div>{revenue}</div>
                    </div>
                    <div style={{display: "flex", flex: 1}}>
                        <div>{notifications}</div>
                    </div>
                </div>
            </div>
        </body>
        </html>
    ): (
        <html lang="en">
            <body>
                <div>
                    {login}
                </div>
            </body>
        </html>
        )
        }
