import {ErrorWrapper} from "@/app/error-wrapper";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ErrorWrapper>
          {children}
        </ErrorWrapper>
      </body>
    </html>
  )
}
